### ISSUE TITLE
Consider the multiple use of the plugin

### ISSUE THREAD

**Issue by jolanta1** [tollwerk/TYPO3-ext-tw_eprivacy#29]
The plugin in TYPO3 should be developed in a way that allows it to be used in multiple instances or sites. Currently, this is not implemented in the existing code.

This contains:
* custom configuration of more than one storage (storagePid)
* add more than one 'cookie_consent'

**Comment by kftw** [comment]
After inspecting the code and playing around this won't be fixed for the time being. The extension is not designed to distinguish between multiple root pages or plugins and I can't guarantee the expected behaviour when changing this.
