### ISSUE TITLE
Cookies from external web applications

### ISSUE THREAD

**Issue by jolanta1** [tollwerk/TYPO3-ext-tw_eprivacy#30]
Its not possible to include cookies from external pages or applications. 

As a good example, you can refer to the panopto video player.

**Comment by kftw** [comment]
Actually, so called third-party cookies are getting blocked by many browser by default. From a technical point of view, you can't delete or block cookies belonging to another host and that's no issue with tw-eprivacy. 

But I took the opportunity to add some features so Subject records for third-party cookies can be marked as such. If marked, the visitors will see additional information.

![Schnappschuss_090524_031452_PM](https://github.com/user-attachments/assets/81bfb29b-3646-40ff-8dca-f7827a719ac7)
