### ISSUE TITLE
Disable caching for Subject->list?

### ISSUE THREAD

**Issue by kftw** [tollwerk/TYPO3-ext-tw_eprivacy#8]
Right now, in *ext_localconf.php*, the "Eprivacy" plugin is configured like this:

```php
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
            'Tollwerk.TwEprivacy',
            'Eprivacy',
            [
                'Subject' => 'list'
            ],
            // non-cacheable actions
            [
                'Subject' => ''
            ]
        );
```

Shouldn't the list action be registered as non-cacheable action so changes after a form submit are visible?

**Comment by jkphl** [comment]
No need for this, as form submissions **must never be cached** by TYPO3.

**Comment by kftw** [comment]
Interesstingly enough, with full caching enabled in TYPO3, my changes will not show up after form submission.

**Comment by jkphl** [comment]
GET or POST submission?

**Comment by kftw** [comment]
POST

**Comment by kftw** [comment]
Ok, disabling caching for the controller action does solve the problem, indeed:

```php
```php
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
            'Tollwerk.TwEprivacy',
            'Eprivacy',
            [
                'Subject' => 'list'
            ],
            // non-cacheable actions
            [
                'Subject' => 'list'
            ]
        );
```

```

**Comment by jkphl** [comment]
I'm not a fan of precautionary disabling caching like this, especially as it didn't make any problems in any of the other installations so far (afaik). Any way to work around this for the particular instance only?

**Comment by kftw** [comment]
Right now I can't think of any other way. It's quite possible that TYPO3 caching is at least partially disabled in all of the other projects so far.

**Comment by jkphl** [comment]
But still: Form submission should **never** be cached ...

**Comment by kftw** [comment]
Maybe it's not necessarily the form submission itself. I still have to check what happens exactly when submitting the form. But everythink works fine when caching for this actions is disabled.

**Comment by jkphl** [comment]
> But everything works fine when caching for this actions is disabled.

Everything but the cache. ;)
